---
- hosts: all
  gather_facts: false
  become: false

  vars:
    _dest_: ./terraform
    aws_region: us-west-1
    instance_type: t2.micro
    instance_ami_id: ami-0b990d3cfca306617
    resource_name: ec2_instance
    instance_name: amazon-linux-sandbox
    
  tasks:
    - name: Ensure _dest_ folder exists
      # Content suggestion provided by Ansible Lightspeed
      ansible.builtin.file:
        path: "{{ _dest_ }}"
        state: directory
        mode: '0755'

    - name: Create a tf file from template aws_ec2.tf.j2
      # Content suggestion provided by Ansible Lightspeed
      ansible.builtin.template:
        src: aws_ec2.tf.j2
        dest: "{{ _dest_ }}/aws_ec2.tf"

    - name: Create terraform project from _dest_ project folder
      cloud.terraform.terraform:
        project_path: '{{ _dest_ }}'
        state: present
        binary_path: /usr/local/bin/terraform






